label: Buttons
status: ready
preview: "@sam-content"
default: "primary"
variants:
  - name: secondary
    context:
      category: alternate
      label: Secondary buttons
      classes: 'usa-button--secondary'

  - name: danger
    context:
      category: alternate
      label: Danger buttons
      classes: 'usa-button--danger'

  - name: base
    context:
      category: alternate
      label: Gray buttons
      classes: 'usa-button--base'

  - name: outline
    context:
      category: outline
      label: Outline buttons
      classes: 'usa-button--outline'

  - name: outline-inverse
    context:
      category: outline-inverse
      label: Outline inverse buttons
      classes: 'usa-button--outline usa-button--inverse'
