label: Header
status: wip

variants:
  - name: default
    label: Default
    status: null

  - name: extended
    label: Extended header
    context:
      header:
        primary:
          search: false
          id_prefix: extended-
          links:
            - text: Current section
              current: true
              links: false
            - text: Section
              links: false

        secondary:
          search: false
          links:
            - icon:
                icon: bars
            - icon:
                icon: bars

  - name: extended-sam
    label: SAM
    context:
      header:
        title: SAM.gov
        logo: '/assets/images/logo-sam.svg'
        notification: true
        primary:
          search: false
          id_prefix: sam-
          links:
            - text: Home
              href: 'javascript:void(0)'
              current: true
              links: false
            - text: Search
              href: 'javascript:void(0)'
              links: false
            - text: Databank
              href: 'javascript:void(0)'
            - text: Data Services
              href: 'javascript:void(0)'
            - text: Help
              href: 'javascript:void(0)'
        secondary:
          search: false
          links:
            - text: Request
              current: true
              notification: true
              icon:
                icon: request
                classes: 'fa-flip-horizontal'
            - text: Notifications
              icon:
                icon: notifications
            - text: Workspace
              icon:
                icon: workspace
            - text: Sign Out
              icon:
                icon: 'log-out'