label: Alerts
status: wip
preview: "@sam-grid"
variants:
  - name: default
    label: Default
    context:
      label:
        classes: "sds-alert"
      icon:
        icon: exclamation
        prefix: fa
  - name: block
    label: Block
    context:
      label:
        classes: "sds-alert--block"
      icon:
        icon: exclamation
        classes: fa-2x
  - name: expanded
    label: Expanded
    context:
      label:
        classes: "sds-alert--expanded"
      buttons:
        - classes: accordion simple-toggle
          modifiers:
            - secondary
          custom: aria-controls="alert-info-extension"
          icon:
            icon: caret-down
            prefix: fa
            classes:
            title: false
        - classes: accordion simple-toggle
          modifiers:
            - secondary
          custom: aria-controls="alert-extension"
          icon:
            icon: caret-down
            prefix: fa
            classes:
            title: false
        - classes: accordion simple-toggle
          modifiers:
            - secondary
          custom: aria-controls="alert-error-extension"
          icon:
            icon: caret-down
            prefix: fa
            classes:
            title: false
  - name: header
    label: Header
    context:
      label:
        classes: "sds-alert--header"
      buttons:
        - custom: aria-controls="alert1"
          modifiers:
            - secondary
          classes: sds-alert--header__close simple-toggle
          icon:
            icon: times
            prefix: fa
            classes:
            title: false
        - custom: aria-controls="alert2"
          modifiers:
            - secondary
          classes: sds-alert--header__close simple-toggle
          icon:
            icon: times
            prefix: fa
            classes:
            title: false
        - custom: aria-controls="alert3"
          modifiers:
            - secondary
          classes: sds-alert--header__close simple-toggle
          icon:
            icon: times
            prefix: fa
            classes:
            title: false
  - name: sticky
    label: Sticky
    context:
      label:
        classes: "sds-alert--sticky"
      icon:
        icon: alert-info
        classes: fa-3x
