label: Alerts
status: wip
preview: "@sam-content"
variants:
  - name: default
    label: Default
    context:
      label:
        classes: "sds-alert"
      icon:
        icon: exclamation
        prefix: fa
  - name: block
    label: Block
    context:
      label:
        classes: "sds-alert--block"
      icon:
        icon: exclamation
        classes: fa-2x

  - name: expanded
    label: Expanded
    context:
      label:
        classes: "sds-alert--expanded"

  - name: header
    label: Header
    context:
      label:
        classes: "sds-alert--header"
