label: Cards
status: wip
preview: "@sam-content"
default: default
notes: A horizontal header may have a title and a button.
context:
  base: sds-card
  title: Contract Opportunities
  colors:
    - title: Plain
    - modifier: base
      title: Base
    - modifier: accent-cool
      title: Accent Cool
    - modifier: accent-warm
      title: Accent Warm
    - modifier: feature
      title: Feature (Secondary)
  header:
    style: left
  modifiers:
    - shadowed
    - bordered
  body: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sed augue lacus viverra vitae. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sed augue lacus viverra vitae.
variants:
  - name: default
    label: Default
  - name: bordered
    label: Bordered No Shadow
    context:
      modifiers:
        - bordered
  - name: shadowed
    label: Shadowed No Border
    context:
      modifiers:
        - shadowed
  - name: no shadow
    label: No Shadow or Border
    context:
      modifiers:
  - name: no header
    label: No Header
    notes: "508: card must have `aria-labelledby` attribute with a corresponding header outside of card"
    context:
      header:
      colors:
        - title: Plain
  - name: link header
    label: Link Header
    notes: Header can be a link.
    context:
      header:
        link: " "
  - name: header icon left
    label: Header Icon Left
    context:
      header:
        icon: book
  - name: header icon stacked
    label: Header Icon Stacked
    context:
      header:
        icon: book
        style: stacked
  - name: header icon centered
    label: Header Icon Centered
    context:
        header:
          icon: book
          style: center
  - name: header button
    label: Header with One Button
    notes: A horizontal card header may have a title and a button.
    context:
      header:
        buttons:
          - modifiers:
            - outline
        style: flex
  - name: header buttons
    label: Header with Two Buttons
    notes: A horizontal card header may have a title and two buttons.
    context:
      header:
        buttons:
          - modifiers:
            - outline
          - modifiers:
            - outline
        style: flex
  - name: header action
    label: Header with Action Button
    notes: A horizontal card header may have an action button. Card headers with actions should have a row modifier "sds-card__header--row"
    context:
      header:
        action: true
        style: row
  - name: vertical
    label: Vertical Header
    notes: A card can have a vertical header
    context:
      modifiers:
        - shadowed
        - bordered
        - vertical
      header:
        icon: question-circle
  - name: list
    label: List
    notes: Card layouts can be used for lists. Don't add bordered modifier to card -- just add to list
    context:
      modifiers:
        - shadowed
        - list
      body:
        list: true
