label: Accordion
status: wip
preview: "@sam"
default: Bordered
context:
  text: accordion
  classes: 'usa-accordion--bordered'
  header: Accordion Button
  body: Congress shall make no law respecting an establishment of religion, or prohibiting the free exercise thereof; or abridging the freedom of speech, or of the press; or the right of the people peaceably to assemble, and to petition the Government for a redress of grievances.
variants:
  - name: multiselectable
    label: Multiselectable
    context:
      multiselect: true
