status: wip
preview: "@sam-content"
default: unordered
notes: "Lists can be ordered, unordered, or unstyled and have icons and/or be links.
See Cards -- List for example of adding adding a list to a card.
Modifiers are unstyled and flex (for icon lists)"
context:
  modifiers:
  items:
    - text: List Item
    - text: List Item
    - text: List Item
variants:
  - name: unordered
    label: Unordered List
  - name: ordered
    label: Ordered List
    context:
      ordered: true
  - name: unstyled
    label: Unstyled List
    context:
      modifiers:
        - unstyled
  - name: icon
    label: Icon List
    context:
      modifiers:
          - unstyled
          - flex
      items:
        - text: List Item
          icon:
            icon: bell
            classes: fa-fw
        - text: List Item
          icon:
            icon: calendar
            classes: fa-fw
        - text: List Item
          icon:
            icon: book
            classes: fa-fw
  - name: icon large
    label: Icon List -- Large
    context:
      modifiers:
          - unstyled
          - flex
      items:
        - text: List Item
          icon:
            icon: bell
            classes: fa-2x fa-fw
        - text: List Item
          icon:
            icon: calendar
            classes: fa-2x fa-fw
        - text: List Item
          icon:
            icon: book
            classes: fa-2x fa-fw
  - name: menu
    label: Menu List
    context:
      modifiers:
          - unstyled
      items:
        - text: List Item
          href: " "
        - text: List Item
          href: " "
        - text: List Item
          href: " "
  - name: menu icon
    label: Menu List with Icons
    context:
      modifiers:
          - unstyled
          - flex
      items:
        - text: List Item
          href: " "
          icon:
            icon: bell
            classes: fa-fw
        - text: Quick start guide for creating a login.gov account
          href: " "
          icon:
            icon: calendar
            classes: fa-fw
        - text: List Item
          href: " "
          icon:
            icon: book
            classes: fa-fw
  - name: menu icon large
    label: Menu List with Icons -- Large
    context:
      modifiers:
          - unstyled
          - flex
      items:
        - text: List Item
          href: " "
          icon:
            icon: bell
            classes: fa-2x fa-fw
        - text: Quick start guide for creating a login.gov account
          href: " "
          icon:
            icon: calendar
            classes: fa-2x fa-fw
        - text: List Item
          href: " "
          icon:
            icon: book
            classes: fa-2x fa-fw
